<?php include_once('function.inc');
	if(!isset($_SESSION['id'])){
		header('Location: error.php');
		exit();
	}
?>
<!DOCTYPE html>
<html class="lockscreen">
	<head>
		<meta charset="UTF-8">
		<title>Lockscreen | Imancha-OS</title>
		<meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
		<!-- bootstrap 3.0.2 -->
		<link href="css/bootstrap.min.css" rel="stylesheet" type="text/css" />
		<!-- font Awesome -->
		<link href="css/font-awesome.min.css" rel="stylesheet" type="text/css" />
		<!-- Theme style -->
		<link href="css/imancha.css" rel="stylesheet" type="text/css" />

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		<!-- Automatic element centering using js -->
		<div class="center">            
			<div class="headline text-center" id="time">
					<!-- Time auto generated by js -->
			</div><!-- /.headline -->

					<?php
						if(isset($_POST['submit'])){
							mysql_open();
							
							$password = $_POST['password'];
							
							$sql = "SELECT * FROM user WHERE ((username='".$_SESSION['username']."' || email='".$_SESSION['username']."') AND password=SHA1('$password')) AND active is NULL LIMIT 1";
              $res = mysql_query($sql) or die(mysql_error());
              
              if(mysql_num_rows($res) == 1){
								sleep(2);
								header("Location: dashboard.php");
								exit();
							}else{
								echo '<div class="alert alert-warning alert-dismissable">                                    
												<i class="fa fa-warning"></i>
												<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times</button>
												<b>Username</b> and <b>Password</b> did not match. Please try again.
											</div>';
							}							
							mysql_close();
						}
					?>
				
			<!-- User name -->
			<div class="lockscreen-name"><?php echo $_SESSION['username']; ?></div>
			
			<!-- START LOCK SCREEN ITEM -->
			<div class="lockscreen-item">
					<!-- lockscreen image -->
					<div class="lockscreen-image">
							<img src="img/avatar3.png" alt="user image"/>
					</div>
					<!-- /.lockscreen-image -->

					<!-- lockscreen credentials (contains the form) -->
					<div class="lockscreen-credentials">   
						<form method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>">
							<div class="input-group">
									<input type="password" name="password" class="form-control" placeholder="password" />
									<div class="input-group-btn">
										<button name="submit" class="btn btn-flat"><i class="fa fa-arrow-right text-muted"></i></button>
									</div>
							</div>
						</form>
					</div><!-- /.lockscreen credentials -->

			</div><!-- /.lockscreen-item -->          
		</div><!-- /.center -->

		<!-- jQuery 2.0.2 -->
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
		<!-- Bootstrap -->
		<script src="js/bootstrap.min.js" type="text/javascript"></script>

		<!-- page script -->
		<script type="text/javascript">
			$(function() {
				startTime();
				$(".center").center();
				$(window).resize(function() {
					$(".center").center();
				});
			});

			/*  */
			function startTime()
			{
				var today = new Date();
				var h = today.getHours();
				var m = today.getMinutes();
				var s = today.getSeconds();

				// add a zero in front of numbers<10
				m = checkTime(m);
				s = checkTime(s);

				//Check for PM and AM
				var day_or_night = (h > 11) ? "PM" : "AM";

				//Convert to 12 hours system
				if (h > 12)
						h -= 12;

				//Add time to the headline and update every 500 milliseconds
				$('#time').html(h + ":" + m + ":" + s + " " + day_or_night);
				setTimeout(function() {
					startTime()
				}, 500);
			}

			function checkTime(i)
			{
				if (i < 10)
				{
					i = "0" + i;
				}
				return i;
			}

			/* CENTER ELEMENTS IN THE SCREEN */
			jQuery.fn.center = function() {
				this.css("position", "absolute");
				this.css("top", Math.max(0, (($(window).height() - $(this).outerHeight()) / 2) +
								$(window).scrollTop()) - 30 + "px");
				this.css("left", Math.max(0, (($(window).width() - $(this).outerWidth()) / 2) +
								$(window).scrollLeft()) + "px");
				return this;
			}
		</script>
	</body>
</html>
